# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a1014590120c797db184c2ac88bbc960eaf073cc10ec13fc8c8a2ea596a862d46f909f028b3a5f069fe4ba119a8e01c887132c605d4723c6746626fc10ff11e

test:
  secret_key_base: 2a932277e2b08c3a26557cdba3b1214db9d940d4bf7dd351c8a1a765f5ec7d7ca08d87512fd3b8b4890694ba3a18739e7094f60f66b5f96f1a72445d2efa09e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
